
package services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserProfileService", targetNamespace = "http://services/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserProfileService {


    /**
     * 
     * @param arg0
     * @return
     *     returns services.UserProfile
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services/UserProfileService/getUserProfilebyIdRequest", output = "http://services/UserProfileService/getUserProfilebyIdResponse")
    public UserProfile getUserProfilebyId(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
